### ISSUE TITLE
Need Assistance with 'Error Getting Channel' Bot Issue

### ISSUE THREAD

**Issue by mitski-shinm** [Qmirdev/EthelMC#1]
```
mitski:EthelMC mitski$ python app.py
2024-03-16 19:07:34 INFO discord.client logging in using static token
2024-03-16 19:07:36 INFO discord.gateway Shard ID None has connected to Gateway (Session ID: a4b684f44b-----------e63cb88fee5).
We have logged in as NeoMC#----
Error getting channel
```
**Hello there, I encountered an error message stating "Error getting channel" after running the bot. I have double-checked my input and I am confident that everything is correct. Can you please help me identify and resolve the issue?**

**Comment by Qmirdev** [comment]
You are correct. It appears that I mistakenly enclosed the Channel ID variables in double quotations, which is causing an error in the bot process and displaying _"error getting channel"_ To resolve this issue, please remove the double quotations from the Channel IDs that are set in the configuration section. For example: `DISCORD_STATUS_CHANNEL = "127312863612398123"` should be corrected to `DISCORD_STATUS_CHANNEL = 127312863612398123` in order to fix the error #https://github.com/Qmirdev/EthelMC/commit/801b31bb9eab52ecfce7a1e1c4408d5a0615be0a
